include_directories(${CMAKE_CURRENT_LIST_DIR})

set(XSTYLES_SOURCES ${CMAKE_CURRENT_LIST_DIR}/xstyles.qrc)

if (DEFINED X_RESOURCES)
    install (DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/qss DESTINATION ${X_RESOURCES} OPTIONAL)
endif()
